### ISSUE TITLE
Specify a license 

### ISSUE THREAD

**Issue by celer** [CorentinDumery/garment-flattening#2]
Hi, 

I can't seem to find a license for this repo, can you specify which license this work is under? 

I believe no license means that:

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

**Comment by celer** [comment]
https://github.com/orgs/community/discussions/82431

Also:

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by CorentinDumery** [comment]
Thanks for reporting and for the resources, and sorry for the oversight, I was certain I had added it years ago. 

I just copied the MIT license to the README. This covers only the code I have written, and not necessarily its dependencies.
